<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>android.view.View (2)</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.view.View</value>
      <webElementGuid>f5e0f414-6ed6-41ec-938f-cd4759a7ffe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a6ae79a7-6298-4f8b-a874-fbfecf9abe21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>package</name>
      <type>Main</type>
      <value>com.bem_unsoed.appsoed</value>
      <webElementGuid>d0894a57-4388-4788-9712-50c8fe490411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>content-desc</name>
      <type>Main</type>
      <value>Lokasi Fakultas
Tentang Fakultas Teknik
Fakultas Teknik terdiri dari 6 program studi yaitu S1 Jurusan Teknik Sipil, S2 Jurusan Teknik Sipil, Jurusan Teknik Elektro, Jurusan Teknik Geologi, Jurusan Informatika, dan Jurusan Teknik Industri. Kampus Fakultas Teknik terletak di Kampus Unsoed Blater, Jalan Mayor Jenderal Sungkono Km. 05, Kalimanah, Purbalingga, Jawa Tengah. Luas Kampus Teknik Blater sekitar 11 (sebelas) hektar dan sampai dengan tahun 2016 sudah berdiri sebanyak 6 (enam) buah gedung, yaitu gedung A, B, C, D, E dan F.
Media Sosial
Informasi lebih lanjut dapat dilihat di :</value>
      <webElementGuid>6981794d-c2f3-4daa-9ca3-345d5b5fb738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checkable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>72799038-aed8-4d66-aab5-db1466f69080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>02a0193b-58fa-48e6-98aa-692c50c583f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>761e9a68-c1cd-40e8-a9ca-316564b95e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f59619b6-d170-4209-a4e4-06bbfdd8c6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6b2d26b9-23e8-4ddb-b732-3fd78c73d670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focused</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f6da413a-4ab6-4a38-9bac-c82ad2fa4590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrollable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>230f6ce0-e3e0-477f-97ee-826543957bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>long-clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>222eee2d-30a7-46eb-a8dc-1b4e0ef6de8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>password</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b575d404-8f38-4102-a382-8d09cf3fd672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>38c39b4f-c9c2-4e72-8bb3-5d152ad24de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e3692b47-ce9b-4bb6-b88e-bc4e0ad148df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>859</value>
      <webElementGuid>d601bad5-8ae0-42e2-85e4-ab0bf90f474d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1080</value>
      <webElementGuid>d258cf12-9865-4629-b0a5-1e1b855347e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1206</value>
      <webElementGuid>185c13ad-8b7b-46b9-943d-bea737442fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bounds</name>
      <type>Main</type>
      <value>[0,859][1080,2065]</value>
      <webElementGuid>d020a65a-91b4-4722-8850-918e4fb827dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5fb4b798-1fda-4253-bcdb-79e087a29c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>resource-id</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>8e471f67-d471-4641-ba66-fcb1ccbeb723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>2036a02b-efee-4046-81aa-4a7b2341cd08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//hierarchy/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.view.View[1]/android.widget.ScrollView[1]/android.view.View[1]</value>
      <webElementGuid>9d08290b-7a61-4db3-8fcc-5f724ff80599</webElementGuid>
   </webElementProperties>
   <locator>Lokasi Fakultas
Tentang Fakultas Teknik
Fakultas Teknik terdiri dari 6 program studi yaitu S1 Jurusan Teknik Sipil, S2 Jurusan Teknik Sipil, Jurusan Teknik Elektro, Jurusan Teknik Geologi, Jurusan Informatika, dan Jurusan Teknik Industri. Kampus Fakultas Teknik terletak di Kampus Unsoed Blater, Jalan Mayor Jenderal Sungkono Km. 05, Kalimanah, Purbalingga, Jawa Tengah. Luas Kampus Teknik Blater sekitar 11 (sebelas) hektar dan sampai dengan tahun 2016 sudah berdiri sebanyak 6 (enam) buah gedung, yaitu gedung A, B, C, D, E dan F.
Media Sosial
Informasi lebih lanjut dapat dilihat di :</locator>
   <locatorStrategy>ACCESSIBILITY</locatorStrategy>
</MobileElementEntity>
